version: '3'
services:
  backend:
    image: "siqsessedge/cnc-api:CNC-v9.2"
    # image: "siqsessedge/cnc-api:mac-m1"

    container_name: "oee_backend"
    environment:
      "ApplicationMode": "edge"
      "EdgeIP": "localhost"
      "CloudIP": "localhost"
      "MachineName": "Machine-1"
    command: /bin/sh -c "/cnc/config_update.sh"
    ports:
      - "8000:8000"
    volumes:
      - "./DockerFiles/JsonDefaultDataBase/:/cnc/App/JsonDataBase/"
      - "./DockerFiles/JsonDataBase/:/cnc/App/LiveJsonDataBase/"
      - "./DockerFiles/JsonConfiguration/:/cnc/App/JsonConfiguration/"
      - "./DockerFiles/ExcelProduction:/cnc/App/Excel"
      - "./DockerFiles/JsonWeb/:/cnc/Webapp/JsonWeb/"
      - "./DockerFiles/Database/:/cnc/Database/"
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
    depends_on:
      - redis
      - mongo
    networks:
      cloud-network:
        ipv4_address: 172.11.0.2
    restart: always
  redis:
    image: "redis:5"
    container_name: "oee_redis"
    ports:
      - "6379:6379"
    networks:
      cloud-network:
        ipv4_address: 172.11.0.3
    restart: always
  mongo:
    image: "mongo:bionic"
    container_name: "oee_mongo"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=devroot
      # - MONGO_INITDB_ROOT_PASSWORD=devroot
      - MONGO_INITDB_DATABASE=CNC
    ports:
      - "27016:27017"
    volumes:
      - './DockerFiles/MongoDB/data:/data/db'
    networks:
      cloud-network:
        ipv4_address: 172.11.0.4
    restart: always
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=172.11.0.4
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      #      - ME_CONFIG_MONGODB_AUTH_USERNAME=devroot
      #      - ME_CONFIG_MONGODB_AUTH_PASSWORD=devroot
      - ME_CONFIG_BASICAUTH_USERNAME=devroot
      - ME_CONFIG_BASICAUTH_PASSWORD=devroot
    depends_on:
      - mongo
    ports:
      - "8888:8081"
    networks:
      cloud-network:
        ipv4_address: 172.11.0.5
    restart: always
  restarter:
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 28800; docker restart oee_backend; done"]
    restart: always
networks:
  cloud-network:
    ipam:
      config:
        - subnet: 172.11.0.0/16
