version: '3.4'
services:
  client:
    image: siqsessedge/oeedashboard:v5.5
    container_name: "oee_dashboard"
    environment:
      NODE_ENV: production
      REACT_APP_NAME: "MACHINE OEE"
      REACT_APP_SOCKET_URL: ws://localhost:8000/ws/app/notifications/
      REACT_APP_SOCKET_WEB_DASHBOARD_URL: ws://localhost:8000/ws/app/webdashboard/
      REACT_APP_SOCKET_WEB_DEVICE_URL: ws://localhost:8000/ws/app/
      REACT_APP_API_URL: http://localhost:8000/
      REACT_APP_siteMode: "edge"
    ports:
      - 9080:80
    restart: always
  restarter:
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 36000; docker restart oee_dashboard; done"]
    restart: always
